FROM golang:1.9.1-alpine3.6 AS builder

WORKDIR /go/src/app
COPY /go/src/app .
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /go/bin/app .

FROM scratch
WORKDIR /go/bin
COPY --from=builder /go/bin/app /go/bin/app
CMD ["./app"]
