version: '3'
services:
   wpx_lookbook-grpc:
    image: golang:1.9.1
    build: ../
    command: realize start
    volumes:
      - ../go:/go
      - ../Makefile:/go/src/app/Makefile
    working_dir: /go/src/app
    environment:
      - APP_ENV=development
      - DEBUG=true
      - DB_URL=mongodb://workplacex-db/workplacex
    ports:
      - "50057:50051"
    links:
      - workplacex-db:mongo
    depends_on:
      - workplacex-db
   workplacex-db:
    image: mongo
    ports:
      - "27017:27017"
    
