// Code generated by protoc-gen-go. DO NOT EDIT.
// source: protos/lookbook/msg.proto

/*
Package lookbook_msg is a generated protocol buffer package.

It is generated from these files:
	protos/lookbook/msg.proto

It has these top-level messages:
	Id
	UsersId
	ItemId
	Lookbook
	NameRequest
	ItemsRequest
	Request
	Response
*/
package lookbook_msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Id struct {
	XId string `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
}

func (m *Id) Reset()                    { *m = Id{} }
func (m *Id) String() string            { return proto.CompactTextString(m) }
func (*Id) ProtoMessage()               {}
func (*Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Id) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

type UsersId struct {
	UsersId string `protobuf:"bytes,1,opt,name=users_id,json=usersId" json:"users_id,omitempty"`
}

func (m *UsersId) Reset()                    { *m = UsersId{} }
func (m *UsersId) String() string            { return proto.CompactTextString(m) }
func (*UsersId) ProtoMessage()               {}
func (*UsersId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UsersId) GetUsersId() string {
	if m != nil {
		return m.UsersId
	}
	return ""
}

type ItemId struct {
	ItemsId string `protobuf:"bytes,1,opt,name=items_id,json=itemsId" json:"items_id,omitempty"`
}

func (m *ItemId) Reset()                    { *m = ItemId{} }
func (m *ItemId) String() string            { return proto.CompactTextString(m) }
func (*ItemId) ProtoMessage()               {}
func (*ItemId) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ItemId) GetItemsId() string {
	if m != nil {
		return m.ItemsId
	}
	return ""
}

type Lookbook struct {
	XId     string   `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	Name    string   `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	UsersId string   `protobuf:"bytes,3,opt,name=users_id,json=usersId" json:"users_id,omitempty"`
	ItemsId []string `protobuf:"bytes,4,rep,name=items_id,json=itemsId" json:"items_id,omitempty"`
}

func (m *Lookbook) Reset()                    { *m = Lookbook{} }
func (m *Lookbook) String() string            { return proto.CompactTextString(m) }
func (*Lookbook) ProtoMessage()               {}
func (*Lookbook) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Lookbook) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *Lookbook) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Lookbook) GetUsersId() string {
	if m != nil {
		return m.UsersId
	}
	return ""
}

func (m *Lookbook) GetItemsId() []string {
	if m != nil {
		return m.ItemsId
	}
	return nil
}

type NameRequest struct {
	XId  string `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *NameRequest) Reset()                    { *m = NameRequest{} }
func (m *NameRequest) String() string            { return proto.CompactTextString(m) }
func (*NameRequest) ProtoMessage()               {}
func (*NameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *NameRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *NameRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ItemsRequest struct {
	XId     string `protobuf:"bytes,1,opt,name=_id,json=Id" json:"_id,omitempty"`
	ItemsId string `protobuf:"bytes,2,opt,name=items_id,json=itemsId" json:"items_id,omitempty"`
}

func (m *ItemsRequest) Reset()                    { *m = ItemsRequest{} }
func (m *ItemsRequest) String() string            { return proto.CompactTextString(m) }
func (*ItemsRequest) ProtoMessage()               {}
func (*ItemsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ItemsRequest) GetXId() string {
	if m != nil {
		return m.XId
	}
	return ""
}

func (m *ItemsRequest) GetItemsId() string {
	if m != nil {
		return m.ItemsId
	}
	return ""
}

type Request struct {
	Q     string `protobuf:"bytes,1,opt,name=q" json:"q,omitempty"`
	Limit int32  `protobuf:"varint,2,opt,name=limit" json:"limit,omitempty"`
	Page  int32  `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	Sort  string `protobuf:"bytes,4,opt,name=sort" json:"sort,omitempty"`
}

func (m *Request) Reset()                    { *m = Request{} }
func (m *Request) String() string            { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()               {}
func (*Request) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Request) GetQ() string {
	if m != nil {
		return m.Q
	}
	return ""
}

func (m *Request) GetLimit() int32 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Request) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *Request) GetSort() string {
	if m != nil {
		return m.Sort
	}
	return ""
}

type Response struct {
	Data []*Lookbook `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Response) GetData() []*Lookbook {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*Id)(nil), "lookbook.msg.Id")
	proto.RegisterType((*UsersId)(nil), "lookbook.msg.UsersId")
	proto.RegisterType((*ItemId)(nil), "lookbook.msg.ItemId")
	proto.RegisterType((*Lookbook)(nil), "lookbook.msg.Lookbook")
	proto.RegisterType((*NameRequest)(nil), "lookbook.msg.NameRequest")
	proto.RegisterType((*ItemsRequest)(nil), "lookbook.msg.ItemsRequest")
	proto.RegisterType((*Request)(nil), "lookbook.msg.Request")
	proto.RegisterType((*Response)(nil), "lookbook.msg.Response")
}

func init() { proto.RegisterFile("protos/lookbook/msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 271 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x4f, 0x6b, 0x83, 0x40,
	0x10, 0xc5, 0xf1, 0x5f, 0xb4, 0x13, 0xa1, 0xb0, 0xb4, 0xc5, 0xdc, 0x64, 0xdb, 0x43, 0xe8, 0xc1,
	0x40, 0x0a, 0x3d, 0xf4, 0x1b, 0x08, 0xa5, 0x87, 0x85, 0x9c, 0x8b, 0x61, 0x07, 0x91, 0x64, 0xb3,
	0xea, 0xac, 0xdf, 0xbf, 0xec, 0x1a, 0xa9, 0x52, 0x0a, 0xb9, 0xbd, 0x7d, 0xbe, 0xc7, 0x6f, 0xc6,
	0x81, 0x4d, 0xdb, 0x6b, 0xa3, 0x69, 0x77, 0xd6, 0xfa, 0x74, 0xd4, 0xfa, 0xb4, 0x53, 0x54, 0x17,
	0xce, 0x63, 0xe9, 0xe4, 0x15, 0x8a, 0x6a, 0xfe, 0x08, 0x7e, 0x29, 0xd9, 0x3d, 0x04, 0xdf, 0x8d,
	0xcc, 0xbc, 0xdc, 0xdb, 0xde, 0x09, 0xbf, 0x94, 0xfc, 0x05, 0xe2, 0x03, 0x61, 0x4f, 0xa5, 0x64,
	0x1b, 0x48, 0x06, 0x2b, 0x7f, 0x03, 0xf1, 0x30, 0x7e, 0xe2, 0xcf, 0xb0, 0x2a, 0x0d, 0xaa, 0x31,
	0xd4, 0x18, 0x54, 0xf3, 0x90, 0x7b, 0x97, 0x92, 0x23, 0x24, 0x9f, 0x57, 0xe2, 0x1f, 0x0e, 0x63,
	0x10, 0x5e, 0x2a, 0x85, 0x99, 0xef, 0x1c, 0xa7, 0x17, 0xc0, 0x60, 0x01, 0x5c, 0x60, 0xc2, 0x3c,
	0x98, 0x63, 0xf6, 0xb0, 0xfe, 0xaa, 0x14, 0x0a, 0xec, 0x06, 0x24, 0x73, 0x13, 0x89, 0x7f, 0x40,
	0x6a, 0xe7, 0xa7, 0x7f, 0x4b, 0x73, 0x9e, 0xbf, 0x5c, 0xeb, 0x00, 0xf1, 0x54, 0x4b, 0xc1, 0xeb,
	0xae, 0x25, 0xaf, 0x63, 0x0f, 0x10, 0x9d, 0x1b, 0xd5, 0x18, 0x57, 0x88, 0xc4, 0xf8, 0xb0, 0xf8,
	0xb6, 0xaa, 0xd1, 0x2d, 0x14, 0x09, 0xa7, 0xad, 0x47, 0xba, 0x37, 0x59, 0x38, 0x8e, 0x64, 0x35,
	0x7f, 0x87, 0x44, 0x20, 0xb5, 0xfa, 0x42, 0xc8, 0x5e, 0x21, 0x94, 0x95, 0xa9, 0x32, 0x2f, 0x0f,
	0xb6, 0xeb, 0xfd, 0x53, 0x31, 0x3f, 0x5c, 0x31, 0xfd, 0x53, 0xe1, 0x32, 0xc7, 0x95, 0x3b, 0xee,
	0xdb, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x03, 0x78, 0x72, 0xc2, 0xf9, 0x01, 0x00, 0x00,
}
